// Code generated by protoc-gen-httpgo. DO NOT EDIT.
// source: user.proto

package protobuf

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	router "github.com/fasthttp/router"
	fasthttp "github.com/valyala/fasthttp"
	url "net/url"
	strconv "strconv"
)

type UserHTTPGoService interface {
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error)
}

func RegisterUserHTTPGoServer(
	_ context.Context,
	r *router.Router,
	h UserHTTPGoService,
	middlewares []func(ctx context.Context, req any, handler func(ctx context.Context, req any) (resp any, err error)) (resp any, err error),
) error {
	var middleware = chainServerMiddlewaresUser(middlewares)
	// register rpc's
	r.GET("/api/user/{id}", func(fastctx *fasthttp.RequestCtx) {
		fastctx.Response.Header.Set("Content-Type", "application/json")
		input, err := buildUserUserGetUserGetUserRequest(fastctx)
		if err != nil {
			fastctx.SetStatusCode(fasthttp.StatusBadRequest)
			respJson, _ := json.Marshal(struct{ Error string }{Error: err.Error()})
			_, _ = fastctx.Write(respJson)
			return
		}
		ctx := context.WithValue(fastctx, "request", fastctx)
		ctx = context.WithValue(ctx, "proto_service", "User")
		ctx = context.WithValue(ctx, "proto_method", "GetUser")
		handler := func(ctx context.Context, req any) (resp any, err error) {
			return h.GetUser(ctx, input)
		}
		var resp any
		if middleware == nil {
			resp, _ = handler(ctx, input)
		} else {
			resp, _ = middleware(ctx, input, handler)
		}
		respJson, _ := json.Marshal(resp)
		_, _ = fastctx.Write(respJson)
	})

	r.POST("/api/user", func(fastctx *fasthttp.RequestCtx) {
		fastctx.Response.Header.Set("Content-Type", "application/json")
		input, err := buildUserUserCreateUserCreateUserRequest(fastctx)
		if err != nil {
			fastctx.SetStatusCode(fasthttp.StatusBadRequest)
			respJson, _ := json.Marshal(struct{ Error string }{Error: err.Error()})
			_, _ = fastctx.Write(respJson)
			return
		}
		ctx := context.WithValue(fastctx, "request", fastctx)
		ctx = context.WithValue(ctx, "proto_service", "User")
		ctx = context.WithValue(ctx, "proto_method", "CreateUser")
		handler := func(ctx context.Context, req any) (resp any, err error) {
			return h.CreateUser(ctx, input)
		}
		var resp any
		if middleware == nil {
			resp, _ = handler(ctx, input)
		} else {
			resp, _ = middleware(ctx, input, handler)
		}
		respJson, _ := json.Marshal(resp)
		_, _ = fastctx.Write(respJson)
	})

	return nil
}

func buildUserUserGetUserGetUserRequest(ctx *fasthttp.RequestCtx) (arg *GetUserRequest, err error) {
	arg = &GetUserRequest{}
	for keyB, valueB := range ctx.QueryArgs().All() {
		var key = string(keyB)
		var value string
		value, err = url.QueryUnescape(string(valueB))
		if err != nil {
			return nil, fmt.Errorf("failed to decode query parameter %s: %w", key, err)
		}
		switch key {
		case "id":
			arg.Id, err = strconv.ParseInt(value, 10, 64)
			if err != nil {
				return nil, fmt.Errorf("conversion failed for parameter id: %w", err)
			}
		default:
			return nil, fmt.Errorf("unknown query parameter %s with value %s", key, value)
		}
	}
	IdStr, ok := ctx.UserValue("id").(string)
	if ok && len(IdStr) != 0 {
		arg.Id, err = strconv.ParseInt(IdStr, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("conversion failed for parameter id: %w", err)
		}
	}

	return arg, err
}

func buildUserUserCreateUserCreateUserRequest(ctx *fasthttp.RequestCtx) (arg *CreateUserRequest, err error) {
	arg = &CreateUserRequest{}
	var body = ctx.PostBody()
	if len(body) > 0 {
		if err = json.Unmarshal(body, arg); err != nil {
			return nil, err
		}
	}
	for keyB, valueB := range ctx.QueryArgs().All() {
		var key = string(keyB)
		var value string
		value, err = url.QueryUnescape(string(valueB))
		if err != nil {
			return nil, fmt.Errorf("failed to decode query parameter %s: %w", key, err)
		}
		switch key {
		case "email":
			arg.Email = value
		case "username":
			arg.Username = value
		case "displayname":
			arg.Displayname = value
		case "password":
			arg.Password = value
		default:
			return nil, fmt.Errorf("unknown query parameter %s with value %s", key, value)
		}
	}
	return arg, err
}

func chainServerMiddlewaresUser(
	middlewares []func(ctx context.Context, req any, handler func(ctx context.Context, req any) (resp any, err error)) (resp any, err error),
) func(ctx context.Context, req any, handler func(ctx context.Context, req any) (resp any, err error)) (resp any, err error) {
	switch len(middlewares) {
	case 0:
		return nil
	case 1:
		return middlewares[0]
	default:
		return func(ctx context.Context, req any, handler func(ctx context.Context, req any) (resp any, err error)) (resp any, err error) {
			return middlewares[0](ctx, req, getChainServerMiddlewareHandlerUser(middlewares, 0, handler))
		}
	}
}

func getChainServerMiddlewareHandlerUser(
	middlewares []func(ctx context.Context, req any, handler func(ctx context.Context, req any) (resp any, err error)) (resp any, err error),
	curr int,
	finalHandler func(ctx context.Context, req any) (resp any, err error),
) func(ctx context.Context, req any) (resp any, err error) {
	if curr == len(middlewares)-1 {
		return finalHandler
	}
	return func(ctx context.Context, req any) (resp any, err error) {
		return middlewares[curr+1](ctx, req, getChainServerMiddlewareHandlerUser(middlewares, curr+1, finalHandler))
	}
}

var _ UserHTTPGoService = &UserHTTPGoClient{}

type UserHTTPGoClient struct {
	cl          *fasthttp.Client
	host        string
	middlewares []func(ctx context.Context, req *fasthttp.Request, handler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error)) (resp *fasthttp.Response, err error)
	middleware  func(ctx context.Context, req *fasthttp.Request, handler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error)) (resp *fasthttp.Response, err error)
}

func GetUserHTTPGoClient(
	_ context.Context,
	cl *fasthttp.Client,
	host string,
	middlewares []func(ctx context.Context, req *fasthttp.Request, handler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error)) (resp *fasthttp.Response, err error),
) (*UserHTTPGoClient, error) {
	return &UserHTTPGoClient{
		cl:          cl,
		host:        host,
		middlewares: middlewares,
		middleware:  chainClientMiddlewaresUser(middlewares),
	}, nil
}

// GetUser register rpc's
func (p *UserHTTPGoClient) GetUser(ctx context.Context, request *GetUserRequest) (resp *UserResponse, err error) {
	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)
	var queryArgs string
	req.SetRequestURI(fmt.Sprintf("%s/api/user/%d%s", p.host, request.Id, queryArgs))
	req.Header.SetMethod("GET")
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	var reqResp *fasthttp.Response
	ctx = context.WithValue(ctx, "proto_service", "User")
	ctx = context.WithValue(ctx, "proto_method", "GetUser")
	var handler = func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error) {
		resp = &fasthttp.Response{}
		err = p.cl.Do(req, resp)
		return resp, err
	}
	if p.middleware == nil {
		if reqResp, err = handler(ctx, req); err != nil {
			return nil, err
		}
	} else {
		if reqResp, err = p.middleware(ctx, req, handler); err != nil {
			return nil, err
		}
	}
	resp = &UserResponse{}
	var respBody = reqResp.Body()
	err = json.Unmarshal(respBody, resp)
	return resp, err
}

func (p *UserHTTPGoClient) CreateUser(ctx context.Context, request *CreateUserRequest) (resp *UserResponse, err error) {
	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)
	var queryArgs string
	var body []byte
	body, err = json.Marshal(request)
	if err != nil {
		return nil, err
	}
	req.SetBody(body)
	req.SetRequestURI(fmt.Sprintf("%s/api/user%s", p.host, queryArgs))
	req.Header.SetMethod("POST")
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	var reqResp *fasthttp.Response
	ctx = context.WithValue(ctx, "proto_service", "User")
	ctx = context.WithValue(ctx, "proto_method", "CreateUser")
	var handler = func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error) {
		resp = &fasthttp.Response{}
		err = p.cl.Do(req, resp)
		return resp, err
	}
	if p.middleware == nil {
		if reqResp, err = handler(ctx, req); err != nil {
			return nil, err
		}
	} else {
		if reqResp, err = p.middleware(ctx, req, handler); err != nil {
			return nil, err
		}
	}
	resp = &UserResponse{}
	var respBody = reqResp.Body()
	err = json.Unmarshal(respBody, resp)
	return resp, err
}

func chainClientMiddlewaresUser(
	middlewares []func(ctx context.Context, req *fasthttp.Request, handler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error)) (resp *fasthttp.Response, err error),
) func(ctx context.Context, req *fasthttp.Request, handler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error)) (resp *fasthttp.Response, err error) {
	switch len(middlewares) {
	case 0:
		return nil
	case 1:
		return middlewares[0]
	default:
		return func(ctx context.Context, req *fasthttp.Request, handler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error)) (resp *fasthttp.Response, err error) {
			return middlewares[0](ctx, req, getChainClientMiddlewareHandlerUser(middlewares, 0, handler))
		}
	}
}

func getChainClientMiddlewareHandlerUser(
	middlewares []func(ctx context.Context, req *fasthttp.Request, handler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error)) (resp *fasthttp.Response, err error),
	curr int,
	finalHandler func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error),
) func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error) {
	if curr == len(middlewares)-1 {
		return finalHandler
	}
	return func(ctx context.Context, req *fasthttp.Request) (resp *fasthttp.Response, err error) {
		return middlewares[curr+1](ctx, req, getChainClientMiddlewareHandlerUser(middlewares, curr+1, finalHandler))
	}
}
